### ISSUE TITLE
Live plotting, when the user updates the UI display the resulting plot

### ISSUE THREAD

**Issue by tisaconundrum2** [USGS-Astrogeology/PyHAT_Point_Spectra_GUI#121]
If possible add interactivity to the plot.

**Comment by tisaconundrum2** [comment]
As a developer, I might be able to leverage the use of state changes in the UI and send a 'signal' to update the UI

**Comment by ryanbanderson** [comment]
Closing this for now. Live plotting is beyond our scope at this point. Maybe revisit someday.
