### ISSUE TITLE
Auto-generate histograms when defining folds.

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PyHAT_Point_Spectra_GUI#152]
This was briefly implemented to make some figures a while back, but in a very "quick and dirty" way, so I commented it out. The function folds_hist in the PySAT spectral_data object handles this. I'd like to have a check box in Stratified Folds which, when checked, produces these plots in the output folder. Optionally also as pop-up figures.

**Comment by ianeece** [comment]
working in debug mode, but not in run mode- not sure why...

**Comment by ianeece** [comment]
now working
