### ISSUE TITLE
LASSO LARS fails to train

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PyHAT_Point_Spectra_GUI#159]
This may be a sklearn version issue.

**Comment by tisaconundrum2** [comment]
Perhaps deprecation problem?

**Comment by ryanbanderson** [comment]
I thought I resolved this but now am running into other issues: "{TypeError}ufunc 'add' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')"

May need to hide LASSO LARS until I have time to resolve this

**Comment by ryanbanderson** [comment]
I'm inclined to just remove LASSO LARS. I think it gets nearly identical solutions to the regular LASSO using coordinate descent. If we want, we can revisit this later and add it back in.
