### ISSUE TITLE
GUI toolbar inactive on OSX

### ISSUE THREAD

**Issue by AustinSanders** [USGS-Astrogeology/PyHAT_Point_Spectra_GUI#196]
The toolbar does not accept any form of input on OSX High Sierra (version 10.13.2).

**Comment by tisaconundrum2** [comment]
Is that the lower part of the UI that runs the modules, or the upper part that inputs the modules?

**Comment by AustinSanders** [comment]
@tisaconundrum2 Sorry for the late reply - I didn't see that I was pinged.  The upper part with "file | edit | options " etc is entirely inactive on my machine.

For example, when I click "file" so that I can add a "load data" module, nothing happens.

**Comment by ryanbanderson** [comment]
I thought PyQt was supposed to be cross-platform? Do you guys have any idea what could cause this issue?

**Comment by tthatcher95** [comment]
This works on OSX High Sierra (version 10.13.6).
