### ISSUE TITLE
Running cross validation multiple times in a row with PLS, results overwrite each other

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PyHAT_Point_Spectra_GUI#203]
We need to uniquely identify CV Results so that they don't overwrite

**Comment by ryanbanderson** [comment]
See Line 137 of CrossValidation.py

**Comment by tisaconundrum2** [comment]
Remind me again why this implementation `self.datakeys.append('CV Results ' + modelkey)` is not sufficient? If we're appending then the data is always getting replaced, right?
