### ISSUE TITLE
Restored Workflows are too wide

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PyHAT_Point_Spectra_GUI#229]
I assume this is being caused by having long strings in certain combo boxes, so when the UI is restored, it gets set to the width of the widest combo box.

**Comment by tisaconundrum2** [comment]
If you're able to could you please post a small screenshot of what that looks like. 
I want to see who the offending module is.

**Comment by ianeece** [comment]
Unable to reproduce issue, closing for now.
