### ISSUE TITLE
Add ability to insert at the beginning of a workflow

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PyHAT_Point_Spectra_GUI#247]
Right now we do "Insert After", so you can't insert something as the first item in the workflow.

**Comment by tisaconundrum2** [comment]
What did you have in mind for how this should look?

**Comment by tisaconundrum2** [comment]
That sounds like a better idea.

**Comment by ianeece** [comment]
This was indirectly fixed when we added the output path module to the main window.
