### ISSUE TITLE
Necessary Documentation to be Finished

### ISSUE THREAD

**Issue by tisaconundrum2** [USGS-Astrogeology/PyHAT_Point_Spectra_GUI#4]
#PYSAT_UI_MODULES
- [ ] __init__.py
- [ ] cv_.py
- [ ] del_layout_.py
- [ ] dim_reduction_.py
- [ ] Error_.py
- [ ] file_outpath_.py
- [ ] get_data_.py
- [ ] get_mask_.py
- [ ] interpolation_.py
- [ ] normalization_.py
- [ ] plot_.py
- [ ] progress_bar_status_.py
- [ ] regression_predict_.py
- [ ] regression_train_.py
- [ ] removenull_.py
- [ ] sm_.py
- [ ] strat_folds_.py
- [ ] write_data_.py

#Top Level
- [ ] __init__.py
- [ ] pysat_func.py
- [ ] pysat_ui.py
- [ ] pysat_main.py
- [ ] UnitTests.py

**Comment by ryanbanderson** [comment]
Let's update this issue and get some documentation in place in the next few months.
