### ISSUE TITLE
Add an informative error for cases when model fit fails due to NaN

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/PyHAT_Point_Spectra_GUI#85]
Right now it just gives the message "There was a problem training the model" which is not very helpful.

**Comment by tisaconundrum2** [comment]
This error is happening in regression.py: 183

    def fit(self, x, y, i=0):
        # if gaussian processes are being used, data dimensionality needs to be reduced before fitting
        if self.method[i] == 'GP':
            if self.reduce_dim == 'ICA':
                print('Reducing dimensionality with ICA')
                do_ica = FastICA(n_components=self.n_components)
                self.do_reduce_dim = do_ica.fit(x)
            if self.reduce_dim == 'PCA':
                print('Reducing dimensionality with PCA')
                do_pca = PCA(n_components=self.n_components)
                self.do_reduce_dim = do_pca.fit(x)
            x = self.do_reduce_dim.transform(x)
        try:
            print('Training model...')

            self.model.fit(x, y)

            if self.ransac:
                self.outliers = np.logical_not(self.model.inlier_mask_)
                print(str(np.sum(self.outliers)) + ' outliers removed with RANSAC')

            # if self.method[i]=='PLS' and self.ransac==False:
            #    self.calc_Qres_Lev(x)
            self.goodfit = True
        except Exception as e:
            print('There was a problem with training the model!')
            print(e)
            self.goodfit = False  # This can happen for GP when dimensionality is reduced too much. Use try/except to handle these cases.

**Comment by ianeece** [comment]
Added specific error message for NANs.  Will close issue when pull request made.
